---
# handlers file for pandjeed.pleroma

  - name: Get dependancies
    expect:
      chdir: /home/pleroma/pleroma
      command: mix deps.get
      responses:
        Hex: yes
    become: yes
    become_user: pleroma
